### ISSUE TITLE
Add locale for es-CO

### ISSUE THREAD

**Issue by lauft** [GothenburgBitFactory/holidata#13]
The following locale needs to be verified/completed:
```
class es_CO(Locale):
    """
    01-01: [NF] Año Nuevo
    05-01: [NF] Día del Trabajo
    07-20: [NF] Grito de Independencia
    08-07: [NF] Batalla de Boyacá
    12-08: [NRF] Inmaculada Concepción
    12-25: [NRF] Navidad
    : [NV] Día de los Reyes Magos
    : [NRV] Día de San José
    : [NRV] Jueves Santo
    : [NRV] Viernes Santo
    : [NRV] Domingo de Pascua
    : [NRV] La Ascensión del Señor
    : [NRV] Corpus Christi
    : [NRV] El Sagrado Corazón de Jesús
    : [NV] San Pedro y San Pablo
    : [NRV] Asunción de la Virgen
    : [NV] Día de la Raza
    : [NRV] Todos los Santos
    : [NV] Independencia de Cartagena
    """

    locale = "es-CO"
    easter_type = EASTER_WESTERN
```
Checklist:
* Are all holidays (i.e. days "which are defined by law on which business or work are suspended or reduced") listed? Can you provide the legal sources which define the holidays?
* Is the spelling correct? Can you maybe provide a translation?
* Are the fixed dates `<month>-<day>` correct?
* If a holiday has a variable date: Is the algorithm to calculate it correct/can you provide it if missing? If it depends on the easter date: Is it the western or orthodox easter date?
* If a holiday is proclaimed by the government: Can you provide the source?
* Are holidays moved to a different date, e.g. if they fall on a saturday/sunday/...? 
* Are holidays observed on a different date (is there a substitute holiday), e.g. if they fall on a saturday/sunday/...?
* Are the flags correct? (`N` = national holiday, defined by law, `R` = holiday with religious background, `F` = holiday with fixed date, `V` = holiday with variable date)
* Have there been any holidays renamed/deleted/created since 2011? If yes, which ones and since when?

**Comment by jorgeegomez** [comment]
@lauft Most of our holidays are of the type "First Monday after _a-specific-date_". I couldn't find in the code or other locales how to specify this.

**Comment by lauft** [comment]
The template looks more or less like this:
```
    def holiday_<holiday name in snake case>(self):
        """1. monday after <date>: [<flags>] <description>"""

        return [Holiday(
            self.locale,
            "",
            SmartDayArrow(self.year, <month>, <day>).shift_to_weekday('monday', order=1, reverse=False),
            "<description>",
            "<flags>"
        )]
```
See e.g. https://github.com/GothenburgBitFactory/holidata/blob/1db24d4aecab7ec7a007720987d84ffb0988b6db/holidata/holidays/de-DE.py#L33

**Comment by jorgeegomez** [comment]
I just modified the pull request with the changes suggested in the review. I'll go through the checklist here:

- [X] All legal National holidays are listed ("business or work are suspended or reduced")
- [X] URL for the governing Law is included in the code, the relevant Law is "Ley 51 de 1983"
- [X] I checked the spelling, and chose the names given by the previous contributor (not all holidays have a defined official name).
- [ ] I could provide a translation. Not sure where it would go in the code.
- [X] Fixed dates are correct, both religious-based and non-religious.
- [X] For variable date holidays, the algorithm seems right, and matches with public available calendars like [Google Calendar](https://calendar.google.com/calendar/embed?src=ZW4uY28jaG9saWRheUBncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20) or [Calendario de Colombia](https://www.calendariodecolombia.com/).
- [X] Easter-based holidays are based on Western Easter.
- [X] Source of government holidays is provided in the code.
- [X] Some holidays are moved to the first Monday after certain date.
- [X] No fixed-date holiday is moved in case it falls on Saturday or Sunday
- [X] I fixed one of the holidays, that had a missing religious flag
- [X] No new holidays or changes have been made since 2011

**Comment by lauft** [comment]
Perfekt! 👍 

The translation is only optional - it saves me the hassle to figure out what e.g. "Viernes Santo" or "Den slovanských věrozvěstů Cyrila a Metoděje" could mean. 😉

**Comment by lauft** [comment]
The data is available now. Thanks for your contribution!
